# NumPy Workshop

**Tarih:** 5 Nisan 2025
**Yer:** BTK Akademi Derin Öğrenme Kursu

---

## 🎯 Konu Başlıkları

- NumPy ile temel dizi işlemleri
- Toplama, ortalama, maksimum gibi işlemler
- Matris yapısı ve yeniden şekillendirme
- Küçük uygulamalar ve analiz örnekleri

---

## 📊 Uygulama: Bölgesel Satış Verisi Analizi

Aşağıdaki veriler, 3 bölgenin 12 aylık satışlarını içermektedir. NumPy kullanarak aşağıdaki soruları yanıtlayacağız.

### Sorular:

1. Dizinin boyutunu ve eleman sayısını inceleyin.
2. Her bölgenin yıllık toplam satışını bulun.
3. Tüm bölgelerin yıllık ortalama satışını hesaplayın.
4. En yüksek ve en düşük satışlar hangi ay ve bölgede gerçekleşmiştir? Satış miktarları nedir?
5. Toplam satışa göre en çok ve en az satış yapılan aylar hangileridir?
6. Her bölgenin aylık satışlarındaki dalgalanmayı (standart sapma) bulun.
7. Satış verilerini (12 ay, 3 bölge) olacak şekilde yeniden düzenleyin.
8. 15 milyon TL’nin üzerindeki satışlar hangi ay ve bölgelerde gerçekleşmiştir?
9. Her bölgenin aylık kümülatif satış toplamlarını hesaplayın.
10. Her bölgenin satışlarının medyanını (ortanca) bulun.
11. Her bölgenin satışlarının varyansını hesaplayın.
12. Tüm satış verilerinde %25 ve %75'lik çeyreklik değerleri bulun.
13. Her bölgenin en çok satış yaptığı ay hangisidir?
14. Satış verilerinden rastgele 5 eleman seçin.
15. Satış verilerini düzleştirerek 1 boyutlu hale getirin.

---


In [74]:
# Sadece NumPy ile Satış Verisi Analizi
import numpy as np
# Veriler
months = ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran',
          'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık']
region_1 = [10, 12, 15, 18, 20, 22, 25, 23, 19, 17, 21, 14]
region_2 = [8, 9, 11, 13, 15, 17, 19, 18, 14, 16, 12, 10]
region_3 = [12, 14, 16, 18, 20, 22, 24, 23, 21, 19, 17, 15]

# Veriyi 12x3'lük bir NumPy dizisine çevirme
data = np.array([region_1, region_2, region_3]).T

In [75]:
# 1. Dizinin boyutu ve eleman sayısı
print("Dizinin boyutu:", data.shape)
print("Dizinin boyutu:", data.ndim)
print("Toplam eleman sayısı:", data.size)

Dizinin boyutu: (12, 3)
Dizinin boyutu: 2
Toplam eleman sayısı: 36


In [76]:
# 2. Her bölgenin yıllık toplam satışı
print("Her bölgenin yıllık toplam satışı:")
total_sales = np.sum(data, axis=0)
for i, total in enumerate(total_sales, 1):
    print(f"Bölge {i}: {total} M TL")

Her bölgenin yıllık toplam satışı:
Bölge 1: 216 M TL
Bölge 2: 162 M TL
Bölge 3: 221 M TL


In [77]:
# 3. Tüm bölgelerin yıllık ortalama satışı
print("Tüm bölgelerin yıllık ortalama satışı:", np.mean(data), "M TL")
print("Bölge 1'in ortalaması:", np.mean(data[:, 0]), "M TL")
print("Bölge 2'nin ortalaması:", np.mean(data[:, 1]), "M TL")
print("Bölge 3'ün ortalaması:", np.mean(data[:, 2]), "M TL")

Tüm bölgelerin yıllık ortalama satışı: 16.63888888888889 M TL
Bölge 1'in ortalaması: 18.0 M TL
Bölge 2'nin ortalaması: 13.5 M TL
Bölge 3'ün ortalaması: 18.416666666666668 M TL


In [78]:
# 4. En yüksek ve en düşük satışlar
max_val = np.max(data)
min_val = np.min(data)
max_idx = np.unravel_index(np.argmax(data), data.shape)
min_idx = np.unravel_index(np.argmin(data), data.shape)
print(f"En yüksek satış: {max_val} M TL ({months[max_idx[0]]}, Bölge {max_idx[1]+1})")
print(f"En düşük satış: {min_val} M TL ({months[min_idx[0]]}, Bölge {min_idx[1]+1})")

En yüksek satış: 25 M TL (Temmuz, Bölge 1)
En düşük satış: 8 M TL (Ocak, Bölge 2)


In [79]:
# 5. Aylık toplamlar üzerinden en çok/en az satış yapılan ay
monthly_totals = np.sum(data, axis=1)
most_idx = np.argmax(monthly_totals)
least_idx = np.argmin(monthly_totals)
print("En çok satış yapılan ay:", months[most_idx], "-", monthly_totals[most_idx], "M TL")
print("En az satış yapılan ay:", months[least_idx], "-", monthly_totals[least_idx], "M TL")


En çok satış yapılan ay: Temmuz - 68 M TL
En az satış yapılan ay: Ocak - 30 M TL


In [90]:
# 6. Her bölgenin standart sapması
print("Her bölgenin aylık satışlardaki standart sapması:")
stds = np.std(data, axis=0)
for i, std in enumerate(stds, 1):
    print(f"Bölge {i}: {std:.3f}")

Her bölgenin aylık satışlardaki standart sapması:
Bölge 1: 4.378
Bölge 2: 3.452
Bölge 3: 3.593


In [81]:
# 7. Yeniden düzenleme (zaten 12x3)
reshaped = data.reshape(12, 3)
print("Yeniden düzenlenmiş veri (12x3):\n", reshaped)

Yeniden düzenlenmiş veri (12x3):
 [[10  8 12]
 [12  9 14]
 [15 11 16]
 [18 13 18]
 [20 15 20]
 [22 17 22]
 [25 19 24]
 [23 18 23]
 [19 14 21]
 [17 16 19]
 [21 12 17]
 [14 10 15]]


In [82]:
# 8. 15 milyon TL üzerindeki satışlar
print("15 M TL üzerindeki satışlar:")
rows, cols = np.where(data > 15)
for r, c in zip(rows, cols):
    print(f"{months[r]} - Bölge {c+1}: {data[r, c]} M TL")

15 M TL üzerindeki satışlar:
Mart - Bölge 3: 16 M TL
Nisan - Bölge 1: 18 M TL
Nisan - Bölge 3: 18 M TL
Mayıs - Bölge 1: 20 M TL
Mayıs - Bölge 3: 20 M TL
Haziran - Bölge 1: 22 M TL
Haziran - Bölge 2: 17 M TL
Haziran - Bölge 3: 22 M TL
Temmuz - Bölge 1: 25 M TL
Temmuz - Bölge 2: 19 M TL
Temmuz - Bölge 3: 24 M TL
Ağustos - Bölge 1: 23 M TL
Ağustos - Bölge 2: 18 M TL
Ağustos - Bölge 3: 23 M TL
Eylül - Bölge 1: 19 M TL
Eylül - Bölge 3: 21 M TL
Ekim - Bölge 1: 17 M TL
Ekim - Bölge 2: 16 M TL
Ekim - Bölge 3: 19 M TL
Kasım - Bölge 1: 21 M TL
Kasım - Bölge 3: 17 M TL


In [83]:
# 9. Kümülatif satış toplamları
print("Her bölgenin aylık kümülatif satış toplamları:")
cumsum = np.cumsum(data, axis=0)
for i in range(12):
    print(f"{months[i]} - Bölge 1: {cumsum[i,0]}, Bölge 2: {cumsum[i,1]}, Bölge 3: {cumsum[i,2]}")

Her bölgenin aylık kümülatif satış toplamları:
Ocak - Bölge 1: 10, Bölge 2: 8, Bölge 3: 12
Şubat - Bölge 1: 22, Bölge 2: 17, Bölge 3: 26
Mart - Bölge 1: 37, Bölge 2: 28, Bölge 3: 42
Nisan - Bölge 1: 55, Bölge 2: 41, Bölge 3: 60
Mayıs - Bölge 1: 75, Bölge 2: 56, Bölge 3: 80
Haziran - Bölge 1: 97, Bölge 2: 73, Bölge 3: 102
Temmuz - Bölge 1: 122, Bölge 2: 92, Bölge 3: 126
Ağustos - Bölge 1: 145, Bölge 2: 110, Bölge 3: 149
Eylül - Bölge 1: 164, Bölge 2: 124, Bölge 3: 170
Ekim - Bölge 1: 181, Bölge 2: 140, Bölge 3: 189
Kasım - Bölge 1: 202, Bölge 2: 152, Bölge 3: 206
Aralık - Bölge 1: 216, Bölge 2: 162, Bölge 3: 221


In [84]:
# 10. Medyan (ortanca)
print("Her bölgenin satışlarının medyanı:")
for i in range(3):
    print(f"Bölge {i+1}: {np.median(data[:, i])} M TL")

Her bölgenin satışlarının medyanı:
Bölge 1: 18.5 M TL
Bölge 2: 13.5 M TL
Bölge 3: 18.5 M TL


In [97]:
# 10.1. Medyan (ortanca) - alternatif
print("Her bölgenin satışlarının medyanı (alternatif):")
print(np.sort(data, axis=1))
print(np.median(data, axis=1))

Her bölgenin satışlarının medyanı (alternatif):
[[ 8 10 12]
 [ 9 12 14]
 [11 15 16]
 [13 18 18]
 [15 20 20]
 [17 22 22]
 [19 24 25]
 [18 23 23]
 [14 19 21]
 [16 17 19]
 [12 17 21]
 [10 14 15]]
[10. 12. 15. 18. 20. 22. 24. 23. 19. 17. 17. 14.]


In [85]:
# 11. Varyans
print("Her bölgenin satışlarının varyansı:")
for i in range(3):
    print(f"Bölge {i+1}: {np.var(data[:, i]):.2f}")

Her bölgenin satışlarının varyansı:
Bölge 1: 19.17
Bölge 2: 11.92
Bölge 3: 12.91


In [86]:
# 12. 25. ve 75. yüzdelikler
flat_data = data.flatten()
q25 = np.percentile(flat_data, 25)
q75 = np.percentile(flat_data, 75)
print("25. yüzdelik:", q25)
print("75. yüzdelik:", q75)

25. yüzdelik: 13.75
75. yüzdelik: 20.0


In [87]:
# 13. En çok satış yapılan ay (bölge bazlı)
print("Her bölgenin en çok satış yaptığı ay:")
for i in range(3):
    idx = np.argmax(data[:, i])
    print(f"Bölge {i+1}: {months[idx]} ({data[idx, i]} M TL)")

Her bölgenin en çok satış yaptığı ay:
Bölge 1: Temmuz (25 M TL)
Bölge 2: Temmuz (19 M TL)
Bölge 3: Temmuz (24 M TL)


In [88]:
# 14. Rastgele 5 eleman seçimi
print("Rastgele 5 satış verisi:")
print(np.random.choice(flat_data, 5, replace=False))

Rastgele 5 satış verisi:
[17 16 18 22 11]


In [89]:
# 15. Düzleştirilmiş veri
print("Düzleştirilmiş veri:")
print(flat_data)

Düzleştirilmiş veri:
[10  8 12 12  9 14 15 11 16 18 13 18 20 15 20 22 17 22 25 19 24 23 18 23
 19 14 21 17 16 19 21 12 17 14 10 15]
