Boyut İndirgeme ( diminsionality reduction) : temel bileşen analizi ( principal Compenent analysis - PCA)
* yüksek boyutlu veri setlerinde özellik sayısını azalatma işlenmidir.
* Amaç:
  * Veri kümrsisin karmaşıklığımı azalatmak7
  * hesaplama maliyetini düşürmek
  * görsellestirmeyi kolaylastırmak 2d veya 3d
  * aşırı öprenmeyi overfitting önlemek
  * özellikler arasındaki çoklu doğrsallık ( multicollinearity ) sorunun çözmek



Temel Bileşen Analizi ( PCA )
* en yaygın boyut indirgeme tekniklerinde biriir
* verideki en büyük varyansı yakalan yeni eksenler temel bileşenler bulut
* özllikler arasındaki korealsyonu azaltır
* doğrusal bir yöntemdir.

PCA çalışma prensini
* 1.Adım: veri setinin ortalamasını al
* 2. adım korvayons marrisi hesaplanir
* 3. adım korvanyans amrisin özvekterleri ve özdeğelrini bulunur
* 4. adım özdeğerlere gmre mzvektler sıralanaır ( en büyükten en kğçğoe )
* 5. adoım ilk k özvektör en büyük özdeğere karşılık gelen sçeilir
* 6. adom veri seti seçilen özvektöerele dönüştürülür
* matematisel alt yapı temel bileşenler özvekler ile orijibal verinin doğrısal kombinasyolarıdır.

PCA de boyut seçimi
* kaç temel bileşen seçileceği önemlidir
* Açıklanan varyans oranı kullanılır.
* Genellikle toplma varyansın % 90 95 imi açıklayan bileşenler seçilir
* Dirsek grafikleri ( elbow plots ) kullanılabilir.

PCA'nın Kullanım alanları
* görüntü sıkıştırma
* yüz tanıma
* genetik veri analizi
* finansal veri analizi
* veri görselleştirme

Feature Selection ( Özellik Seçimi ) ile Dimensionality Reduction ( Boyut İndirgeme ) Arasındaki Farklar
* Amaç: En önemli özellikleri seçmek / Daha az özellik ile veri setini temsil etmek
* Yöntem: En önemli özelliği seç diğerini at / Özellikleri matematiksel olarak birleştirierek yenisini oluşturur.
* Sonuç: Seçilen özellikler orijinal ,özgündür,özelliklerdir / Özellikler Özgünlüğnü kaybeder
* Yorumlanabilir: Yorumlanabiliği yüksek olabilir / Yorumlanabilirlik azalır
* Örnekler: SelectKBest, Recursive Feature Elimination / PCA, t-SNE

In [4]:
# Gerekli kütüphaneleri import edelim
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [5]:
# Örnek veri setini oluşturalım ( 2 Boyutlu )
data = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

In [8]:
# Veriyi ölçeklendir
sc = StandardScaler()
data_scaled = sc.fit_transform(data)
print("Ölçeklendirilmiş veri:\n", data_scaled)

Ölçeklendirilmiş veri:
 [[-1.34164079 -1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079  1.34164079]]


In [7]:
# PCA Uygula ( 2 Özelliğe indir )
pca = PCA(n_components=2)
data_pca = pca.fit_transform(data_scaled)
print("PCA uygulanmış veri:\n", data_pca)

PCA uygulanmış veri:
 [[-2.68328157e+00 -2.30564743e-16]
 [-8.94427191e-01  4.97701844e-17]
 [ 8.94427191e-01 -4.97701844e-17]
 [ 2.68328157e+00 -1.97384620e-16]]
