# Veri Ön İşleme ( Preprocessing )

# İmputasyon ( Doldurma) nedir?
Eksik verilerin yerine tahmin edilen veya hesaplnana değerler koyma işlemidir.
Amaç: Veri kaybını önlemek,modelin daha iyi performans göstermesini sağlamak.

SimpleImputer kullanımı
* scikitlearn kütüphanesinden SimpleImputer sınıfını kullanarak eksik verileri doldurabiliriz.
* Eksik verileri ortalama medyan veya en sık değer mod ile doldurabilir.
*  Sayısal ve kategorik veriler için gfarklı statejiler uygulanabilir.
*  strategy parametresi ile doldurma yönntemi belirlenir:
    * mean: Ortalama ile doldurma ( sayısal veriler için)
    * median: Medyan ile doldurma ( sayısal veriler için)
    * most_frequent: En sık değer ile doldurma ( kategorik veya sayısal veriler için)
    * constant: Sabit bir değer ile doldurma ( sayısal veya kategorik veriler için)
* fill_value parametresi, constant seç,ldiği zaman dolduraak olan değeri belirler

In [6]:
# Gerekli kütüphaneleri import et
import numpy as np
from sklearn.impute import SimpleImputer

In [7]:
# Örnek veri seti oluştur
data = np.array([[1, 2, np.nan],
                [3, np.nan, 6],
                [7, 8, 9],
                [np.nan, 11, 12]])

In [8]:
# SimpleImputer objesi oluştur
imputer = SimpleImputer(strategy='mean')
# SimpleImputer objesini fit et ve veriyi dönüştür
data_imputed_mean = imputer.fit_transform(data)

print(data_imputed_mean)

[[ 1.          2.          9.        ]
 [ 3.          7.          6.        ]
 [ 7.          8.          9.        ]
 [ 3.66666667 11.         12.        ]]


In [9]:
# SimpleImputer objesi oluştur
imputer = SimpleImputer(strategy='median')
# SimpleImputer objesini fit et ve veriyi dönüştür
data_imputed_median = imputer.fit_transform(data)

print(data_imputed_median)

[[ 1.  2.  9.]
 [ 3.  8.  6.]
 [ 7.  8.  9.]
 [ 3. 11. 12.]]


# Veri Dönüşümü ( Transformation )
* mevcut özellikler kullanılarak yeni özellikler oluşturma işlemidir.
* Amaç: Modelin karmaşıklığını artırmaki veri setinde bulunmaya ilkileri ortaya çıkarmak.
* modelin çğrenme kapasitesini artırır.

 Veri Dönüşümü ( Transformation ) - PolynomialFeatures
* Özelliklerin polinomlarını oluşturur.
* Özelliklerin çarpımlarını ve kuvvetlerini oluşturur.
* Özelliklerin etkileşimlerini yakalar.

 Veri Dönüşümü ( Transformation ) - FunctionTransformer
* Kullanıcı tanımlı bir fonksiyonu veri setine uygular.
* Logaritmik üstel veya trigionmetrik dföünüşmler gibi özel durumlarda kullanılır.
* func parametresi ile uygulanacak fonksiyon belirtlir.

 Veri Dönüşümü ( Transformation ) - Karşılaştırma
* PolynomialFeatures: Mofrlein karşmaşılpını artırmak için pılinem özellikleri ouşturur.
* function transformer verilere özel fonksiyonlar uyugularayak özel dönüşümler sağlar.

Veri Dönüşümü ( Transformation ) - PolynomialFeatures

In [10]:
# Gerekli kütüphaneleri import et
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [12]:
# Örnek veri seti oluştur
data = np.array([[2, 3],
                [4, 5],
                [6, 7]])
print(data)

[[2 3]
 [4 5]
 [6 7]]


In [13]:
# PolynomialFeatures objesi oluştur
poly = PolynomialFeatures(degree=2)
# PolynomialFeatures objesini fit et ve veriyi dönüştür
data_poly = poly.fit_transform(data)

print("Polinomal veri: \n", data_poly)

Polinomal veri: 
 [[ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]
 [ 1.  6.  7. 36. 42. 49.]]


Veri Dönüşümü ( Transformation ) - FunctionTransformer

In [14]:
# Gerekli kütüphaneleri import et
import numpy as np
from sklearn.preprocessing import FunctionTransformer

In [15]:
# Örnek veri seti oluştur
data = np.array([[1, 2],
                [3, 4],
                [5, 6]])

In [16]:
# Kullanıcı tanımlı fonksiyon
log_transform = FunctionTransformer(np.log1p) # log1p: log(1+x) dönüşümü
# Fonksiyonu veriye uygula
data_log = log_transform.fit_transform(data)
print(data_log)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]
 [1.79175947 1.94591015]]
