5 April 2025
Week 1 Day 1

Creating own data.

In [1]:
import numpy as np

In [2]:
months = ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık']
region_1 = [10, 12, 15, 18, 20, 22, 25, 23, 19, 17, 12, 14]
region_2 = [8, 9, 11, 13, 15, 17, 19, 18, 14, 12, 17, 10]
region_3 = [12, 14, 16, 18, 20, 22, 24, 23, 21, 19, 17, 15]
data = np.array([region_1, region_2, region_3]).T

In [3]:
data

array([[10,  8, 12],
       [12,  9, 14],
       [15, 11, 16],
       [18, 13, 18],
       [20, 15, 20],
       [22, 17, 22],
       [25, 19, 24],
       [23, 18, 23],
       [19, 14, 21],
       [17, 12, 19],
       [12, 17, 17],
       [14, 10, 15]])

In [5]:
# 1. Dizinin boyutunu ve eleman sayısını inceleyelim.
data.shape, data.size

((12, 3), 36)

In [20]:
# 2. Her bölgenin yıllık toplam satışı nedir?
total_sales = data.sum(axis=0)
total_sales

array([207, 163, 221])

In [23]:
# 3. Tüm bölgelerin yıllık ortlama satışı nedir?
average_sales = data.mean(axis=0)
average_sales

array([17.25      , 13.58333333, 18.41666667])

In [24]:
# 4. En yüksek ve en düşük aylık satışlar hangi aylarda gerçekleşmitir ve miktarları nedir?
highest_sales = data.max(axis=0)
lowest_sales = data.min(axis=0)
highest_sales_month = np.array(months)[np.argmax(highest_sales)]
lowest_sales_month = np.array(months)[np.argmin(lowest_sales)]
highest_sales_value = highest_sales.max()
lowest_sales_value = lowest_sales.min()
highest_sales_month, highest_sales_value, lowest_sales_month, lowest_sales_value

(np.str_('Ocak'), np.int64(25), np.str_('Şubat'), np.int64(8))

In [25]:
# 5. En çok ve en az satış yapılan aylar hangileridir?
highest_month = months[np.argmax(highest_sales)]
lowest_month = months[np.argmin(highest_sales)]
highest_sales_value = highest_sales.max()
lowest_sales_value = highest_sales.min()
lowest_month, lowest_sales_value

('Şubat', np.int64(19))

In [26]:
# 6. Her bölgenin aylık satışlarındaki dalganalnma ( starndart sapma ) ne kadardır?
std_deviation = data.std(axis=0)
std_deviation

array([4.56663625, 3.52274356, 3.59301019])

In [27]:
# 7. Satış verileri farklı bir formatta ( 12 ay 3 bölge ) nasıl yeniden düzenlenebilir?
reshaped_data = data.reshape(12, 3)
reshaped_data


array([[10,  8, 12],
       [12,  9, 14],
       [15, 11, 16],
       [18, 13, 18],
       [20, 15, 20],
       [22, 17, 22],
       [25, 19, 24],
       [23, 18, 23],
       [19, 14, 21],
       [17, 12, 19],
       [12, 17, 17],
       [14, 10, 15]])

In [30]:
# 8. 15 Milyon TL'nin üzerindeki satışlar hangi aylarda ve bölgelerde gerçekleşmiştir?
high_sales_mask = data > 15
high_sales_indices = np.argwhere(high_sales_mask)
high_sales_months = [months[i] for i, j in high_sales_indices]
high_sales_regions = high_sales_indices[:, 1]
high_sales_values = data[high_sales_mask]
high_sales_info = list(zip(high_sales_months, high_sales_regions, high_sales_values))
high_sales_info

[('Mart', np.int64(2), np.int64(16)),
 ('Nisan', np.int64(0), np.int64(18)),
 ('Nisan', np.int64(2), np.int64(18)),
 ('Mayıs', np.int64(0), np.int64(20)),
 ('Mayıs', np.int64(2), np.int64(20)),
 ('Haziran', np.int64(0), np.int64(22)),
 ('Haziran', np.int64(1), np.int64(17)),
 ('Haziran', np.int64(2), np.int64(22)),
 ('Temmuz', np.int64(0), np.int64(25)),
 ('Temmuz', np.int64(1), np.int64(19)),
 ('Temmuz', np.int64(2), np.int64(24)),
 ('Ağustos', np.int64(0), np.int64(23)),
 ('Ağustos', np.int64(1), np.int64(18)),
 ('Ağustos', np.int64(2), np.int64(23)),
 ('Eylül', np.int64(0), np.int64(19)),
 ('Eylül', np.int64(2), np.int64(21)),
 ('Ekim', np.int64(0), np.int64(17)),
 ('Ekim', np.int64(2), np.int64(19)),
 ('Kasım', np.int64(1), np.int64(17)),
 ('Kasım', np.int64(2), np.int64(17))]

In [31]:
# 9. Her bölgenin aylık kümülatif satış toplamları nelerdir?
cumulative_sales = np.cumsum(data, axis=0)
cumulative_sales

array([[ 10,   8,  12],
       [ 22,  17,  26],
       [ 37,  28,  42],
       [ 55,  41,  60],
       [ 75,  56,  80],
       [ 97,  73, 102],
       [122,  92, 126],
       [145, 110, 149],
       [164, 124, 170],
       [181, 136, 189],
       [193, 153, 206],
       [207, 163, 221]])

In [32]:
# 10. Her bölgenin satışlarının medyanı ( ortanca ) nedir?
median_sales = np.median(data, axis=0)
median_sales

array([17.5, 13.5, 18.5])

In [33]:
# 11. Her bölgenin satışlarını varyansı nedir?
variance_sales = np.var(data, axis=0)
variance_sales

array([20.85416667, 12.40972222, 12.90972222])

In [34]:
# 12. Tüm satış verillerimnde 25. ve 75. yüzdelik dilimleri ( çeyreklikler ) nedir?
percentiles = np.percentile(data, [25, 75], axis=0)
percentiles_25 = percentiles[0]
percentiles_75 = percentiles[1]
percentiles_25, percentiles_75

(array([13.5 , 10.75, 15.75]), array([20.5 , 17.  , 21.25]))

In [35]:
# 13. Her bölgenin en çok satış yaptığı ay hangisidir?
highest_sales_region = np.argmax(data, axis=0)
highest_sales_month = np.array(months)[highest_sales_region]
highest_sales_month

array(['Temmuz', 'Temmuz', 'Temmuz'], dtype='<U7')

In [36]:
# 14. Satış verilerinden rastgele 5 eleman seçelim.
random_indices = np.random.choice(data.size, 5, replace=False)
random_elements = data.flatten()[random_indices]
random_elements

array([17, 17, 20, 14, 17])

In [37]:
# 15. Satış verilerini düzleştirin (1 boyutlu diziye dönüştürün.)
flattened_data = data.flatten()
flattened_data

array([10,  8, 12, 12,  9, 14, 15, 11, 16, 18, 13, 18, 20, 15, 20, 22, 17,
       22, 25, 19, 24, 23, 18, 23, 19, 14, 21, 17, 12, 19, 12, 17, 17, 14,
       10, 15])